# Generated by Django 2.2.5 on 2019-09-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='raiting',
        ),
        migrations.AddField(
            model_name='news',
            name='rating',
            field=models.IntegerField(default=0, editable=False, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='watches',
            field=models.IntegerField(default=0, editable=False, verbose_name='Просмотры'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=30, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Контент коментария')),
                ('rating', models.IntegerField(editable=False, verbose_name='Рейтинг коментария')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenta.News', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['auth_name'],
            },
        ),
    ]
