# Generated by Django 2.2.5 on 2019-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0003_news_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='shoet_content',
            field=models.CharField(default=' ', max_length=100, verbose_name='раткое описание'),
        ),
    ]
