# Generated by Django 2.2.5 on 2019-09-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0004_news_shoet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='newsimage',
        ),
        migrations.AddField(
            model_name='news',
            name='main_image',
            field=models.ImageField(default=None, upload_to='static/images/', verbose_name='Основное изображение статьи'),
        ),
    ]
