# Generated by Django 2.2.5 on 2019-09-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0005_auto_20190917_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(upload_to='static/images/', verbose_name='Основное изображение статьи'),
        ),
    ]
