# Generated by Django 2.2.5 on 2019-09-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0006_auto_20190917_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок статьи'),
        ),
    ]
